//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2020602883_PhanThiLanAnh_Tao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhanvien
    {
        public string MaNV { get; set; }
        public string HoTen { get; set; }
        public string TrinhDo { get; set; }
        public Nullable<int> Luong { get; set; }
    }
}
